Config for Pianoteq New realtime frontends.

diff --git a/zynthian-stage/bin/move_realtime b/zynthian-stage/bin/move_realtime
--- a/zynthian-stage/bin/move_realtime
+++ b/zynthian-stage/bin/move_realtime
@@ -6,12 +6,19 @@ CPUS="#1-3" # CPU0 is nrt
 
 if [ ! -e ${PARTRT} -o ! -e ${BITCALC} ]
 then
-	echo "No realtime tools (partrt/bitcalc) found - starting non-realtime." >&1
+	echo "No realtime tools (partrt/bitcalc) found - doing nothing."
+	exit 0
+fi
+
+if [[ `ps ax | grep ${0} | grep -v grep | wc -l` == 0 ]]
+then
+	echo "PID ${0} not found."
+	exit 10
 fi
 
 if [ -z "${1}" ]
 then
-	echo "Usage: ${0} <program>"
+	echo "Usage: ${0} <PID-of-RT-process>"
 	exit 1
 fi
 
@@ -20,4 +27,4 @@ then
 	${PARTRT} create 0x`${BITCALC} ${CPUS}`
 fi
 
-${PARTRT} run -f99 rt "${1}"
+${PARTRT} move "${1}" rt
